name: Build kernel

on:
  push:


jobs:

  guamp:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Start
      run: |
        ./compile.sh guamp

  cebu:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Start
      run: |
        ./compile.sh cebu
